FROM docker.elastic.co/logstash/logstash:8.1.0

# Add your logstash plugins setup here

# to build with
# docker build . --tag projtap:logstash
# and run with 
# docker run --rm -it -v $PWD/pipeline/:/usr/share/logstash/pipeline/ projtap:logstash
# make sure that pipeline dir with proper conf is there

